language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: Ll85oG2TsfKyNJxOGuXOn9ikb7MJHVgK3RyrAIjlDifLoQaDm2QLL2dIhn4tSdCem9yu1P2kYdVQmHyxnKMhQfy4DUAWG/BhCR92+7nwDuyUHIhm7JeD+JeurlfScIb1jVQ+q6gBSijvibHmJO1R2jQIfN9baFDxR6hzsxtgOeCeleUMCamf7TMjxkk2xGXkKAI0m8J2jr67HT2yfHIDsfMtEFnlB8hxGWson5gwt7Yz/qdAgA/Auj8cpmDGNbz2j3f7ABl1obY+zUi/ej7iW0akrmHS2SaFkTTKHW592XcF5En0sdnRJPBQxfhbijW6vEbZ/QkINT9suL0zVI9373PHFWLqx3LsUseODQULZLFIJfc5c76N8yHM3lyxDtNS+Pz/czFG+dYZt4zURpsPK9LRmND6OXFe6kO3PhEcBUwiaYXBDQEJ5L5gpWr50zCH5WelbXUsoGMRpGWysXkkw6NUCgtBXNNCy3tuOb6IWU/ux7H2WyQiBW4ejfABiedywfJ1ciYtymgFgs/tjd9s+HVoGRgnsg9lSDYbGlnwJk+hbq8uWA3XymOJHoz3njX2wWrH/K4/b7TW1hN3Wduz5JsB4shesVXbU1S+8Ba16jfNKzT8PBSgfCDrkfQYGUWjuLVoafuduMjByPkinfdpmRxrNDTSKtyPLsB5xGZGFlM=
  app: my-java-app
